/**
 * @file mock-data.ts
 * @description Dados de demonstração para desenvolvimento e testes do Acelera Auto CRM.
 *
 * Contém 8 veículos e 10 leads realistas + funções utilitárias para criar e
 * atualizar veículos no estado local (pré-Supabase).
 */

import type {
  Lead,
  Vehicle,
  VehicleFormData,
  VehicleStatus,
  Client,
  ClientFormData,
} from "@/types/crm";

// ---------------------------------------------------------------------------
// Veículos de demonstração
// ---------------------------------------------------------------------------
// Veículos de demonstração (15 veículos realistas)
// ---------------------------------------------------------------------------

export const mockVehicles: Vehicle[] = [
  {
    id: "v-001",
    make: "Honda",
    model: "Civic",
    version: "EXL 2.0 Flex Aut.",
    yearFab: 2022,
    yearModel: 2023,
    plate: "BRA-2E22",
    km: 18500,
    price: 149900,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80",
    daysInStock: 12,
    fipePrice: 148000,
    estimatedMargin: 14500,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-002",
    make: "Toyota",
    model: "Corolla",
    version: "XEI 2.0 Flex Aut.",
    yearFab: 2021,
    yearModel: 2022,
    plate: "CDA-3F19",
    km: 34200,
    price: 134900,
    status: "reservado",
    imageUrl:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
    daysInStock: 8,
    fipePrice: 133500,
    estimatedMargin: 12000,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-003",
    make: "Jeep",
    model: "Compass",
    version: "Longitude 1.3 Turbo Flex Aut.",
    yearFab: 2023,
    yearModel: 2023,
    plate: "EFC-4G77",
    km: 21000,
    price: 168000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    daysInStock: 42,
    fipePrice: 166000,
    estimatedMargin: 16000,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-004",
    make: "Volkswagen",
    model: "T-Cross",
    version: "Highline 1.4 TSI Aut.",
    yearFab: 2022,
    yearModel: 2023,
    plate: "GHI-5J44",
    km: 22100,
    price: 129900,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    daysInStock: 15,
    fipePrice: 128000,
    estimatedMargin: 11500,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-005",
    make: "Fiat",
    model: "Pulse",
    version: "Audace 1.0 Turbo Flex Aut.",
    yearFab: 2023,
    yearModel: 2024,
    plate: "JKL-6M55",
    km: 19500,
    price: 98500,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
    daysInStock: 68,
    fipePrice: 97000,
    estimatedMargin: 9800,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-006",
    make: "Chevrolet",
    model: "Onix",
    version: "Premier 1.0 Turbo Aut.",
    yearFab: 2022,
    yearModel: 2022,
    plate: "MNO-7P33",
    km: 41000,
    price: 84900,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
    daysInStock: 24,
    fipePrice: 83000,
    estimatedMargin: 8200,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-007",
    make: "Hyundai",
    model: "Creta",
    version: "Ultimate 2.0 Flex Aut.",
    yearFab: 2023,
    yearModel: 2023,
    plate: "PQR-8S11",
    km: 27400,
    price: 144000,
    status: "reservado",
    imageUrl:
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    daysInStock: 19,
    fipePrice: 142000,
    estimatedMargin: 13800,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-008",
    make: "Honda",
    model: "HR-V",
    version: "EXL 1.5 Flex Aut.",
    yearFab: 2023,
    yearModel: 2023,
    plate: "BCP-9A12",
    km: 25800,
    price: 139900,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    daysInStock: 10,
    fipePrice: 138500,
    estimatedMargin: 12900,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-009",
    make: "Toyota",
    model: "Corolla Cross",
    version: "Altis Hybrid 1.8 Aut.",
    yearFab: 2022,
    yearModel: 2023,
    plate: "HYB-1D88",
    km: 31000,
    price: 162000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    daysInStock: 65,
    fipePrice: 160000,
    estimatedMargin: 15000,
    fuel: "Híbrido",
    transmission: "Automático",
  },
  {
    id: "v-010",
    make: "Jeep",
    model: "Commander",
    version: "Série S 1.3 Turbo Aut.",
    yearFab: 2022,
    yearModel: 2022,
    plate: "JPS-4E56",
    km: 38000,
    price: 178000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80",
    daysInStock: 35,
    fipePrice: 175000,
    estimatedMargin: 17500,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-011",
    make: "Volkswagen",
    model: "Nivus",
    version: "Highline 1.0 TSI Aut.",
    yearFab: 2023,
    yearModel: 2023,
    plate: "NVX-2C40",
    km: 26300,
    price: 128000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80",
    daysInStock: 7,
    fipePrice: 126000,
    estimatedMargin: 11000,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-012",
    make: "Chevrolet",
    model: "Tracker",
    version: "Premier 1.2 Turbo Aut.",
    yearFab: 2023,
    yearModel: 2023,
    plate: "TRK-8B90",
    km: 22000,
    price: 119900,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    daysInStock: 48,
    fipePrice: 118000,
    estimatedMargin: 10500,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-013",
    make: "Fiat",
    model: "Fastback",
    version: "Limited Edition 1.3 Turbo Aut.",
    yearFab: 2023,
    yearModel: 2024,
    plate: "FBK-5H77",
    km: 18200,
    price: 136000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
    daysInStock: 14,
    fipePrice: 134000,
    estimatedMargin: 13000,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-014",
    make: "Nissan",
    model: "Kicks",
    version: "Exclusive 1.6 Flex Aut.",
    yearFab: 2022,
    yearModel: 2023,
    plate: "KCK-3F21",
    km: 36500,
    price: 118000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80",
    daysInStock: 29,
    fipePrice: 116000,
    estimatedMargin: 10200,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-015",
    make: "BMW",
    model: "320i",
    version: "M Sport 2.0 Turbo Aut.",
    yearFab: 2022,
    yearModel: 2022,
    plate: "BMW-3M20",
    km: 29000,
    price: 269000,
    status: "disponivel",
    imageUrl:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=800&q=80",
    daysInStock: 52,
    fipePrice: 265000,
    estimatedMargin: 24000,
    fuel: "Flex",
    transmission: "Automático",
  },
  {
    id: "v-016",
    make: "Renault",
    model: "Kwid",
    version: "Intense 1.0 Flex Aut.",
    yearFab: 2021,
    yearModel: 2022,
    plate: "STU-9V99",
    km: 52300,
    price: 59900,
    status: "vendido",
    imageUrl:
      "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80",
    daysInStock: 60,
    fipePrice: 58500,
    estimatedMargin: 6500,
    fuel: "Flex",
    transmission: "Automático",
  },
];

// ---------------------------------------------------------------------------
// Funções utilitárias para estado local (pre-Supabase)
// ---------------------------------------------------------------------------

/**
 * Cria um novo veículo a partir dos dados do formulário, gerando um `id` único.
 *
 * @param data - Dados do formulário sem `id`.
 * @returns Objeto `Vehicle` completo com `id` gerado.
 */
export function createVehicle(data: VehicleFormData): Vehicle {
  return {
    id: `v-${Date.now()}`,
    ...data,
  };
}

/**
 * Atualiza o status de um veículo numa lista imutável.
 *
 * @param vehicles - Lista de veículos atual.
 * @param id - ID do veículo a atualizar.
 * @param status - Novo status.
 * @returns Nova lista com o veículo atualizado.
 */
export function updateVehicleStatus(
  vehicles: Vehicle[],
  id: string,
  status: VehicleStatus
): Vehicle[] {
  return vehicles.map((v) => (v.id === id ? { ...v, status } : v));
}

/**
 * Formata um número como moeda Brasileira (BRL).
 *
 * @param value - Valor em Reais.
 * @returns String formatada, ex: "R$\u00a0149.900".
 */
export function formatCurrency(value: number): string {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

/**
 * Formata quilometragem com separador de milhar.
 *
 * @param km - Quilometragem.
 * @returns String formatada, ex: "18.500 km".
 */
export function formatKm(km: number): string {
  return `${new Intl.NumberFormat("pt-BR").format(km)} km`;
}

// ---------------------------------------------------------------------------
// Leads de demonstração (Cenário Concessionária Viva - 33 leads)
// ---------------------------------------------------------------------------

const now = Date.now();

export const mockLeads: Lead[] = [
  // --- 1. Novos Leads (Roleta) - 3 leads com SLA estourado > 15 min ---
  {
    id: "l-001",
    name: "João Ferreira",
    phone: "11988887777",
    email: "joao.ferreira@email.com",
    vehicleInterest: "Jeep Compass Longitude 2023",
    status: "novo",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 22 * 60 * 1000).toISOString(),
    lastContactAt: null,
    origin: "webmotors",
    estimatedValue: 168000,
    notes: "Aguardando primeiro contato há 22 min via Webmotors.",
  },
  {
    id: "l-002",
    name: "Marcos Paulo",
    phone: "11977778888",
    email: "marcos.paulo@email.com",
    vehicleInterest: "Honda HR-V EXL 2023",
    status: "novo",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 28 * 60 * 1000).toISOString(),
    lastContactAt: null,
    origin: "instagram",
    estimatedValue: 139900,
    notes: "Lead vindo do Instagram / Meta Ads querendo agendar visita.",
  },
  {
    id: "l-003",
    name: "Renata Silveira",
    phone: "11966669999",
    email: "renata.silveira@email.com",
    vehicleInterest: "Fiat Pulse Audace 2024",
    status: "novo",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 19 * 60 * 1000).toISOString(),
    lastContactAt: null,
    origin: "webmotors",
    estimatedValue: 98500,
    notes: "Interesse com veículo usado na troca.",
  },

  // --- 2. Primeiro Contato / Atendimento (Leads Quentes) ---
  {
    id: "l-004",
    name: "Felipe Guimarães",
    phone: "11955551111",
    email: "felipe.g@email.com",
    vehicleInterest: "Hyundai Creta Ultimate 2023",
    status: "atendimento",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 45 * 60 * 1000).toISOString(),
    lastContactAt: new Date(now - 30 * 60 * 1000).toISOString(),
    origin: "whatsapp",
    estimatedValue: 144000,
    notes: "Qualificado via WhatsApp, analisando cores disponíveis.",
  },
  {
    id: "l-005",
    name: "Carlos Mendonça",
    phone: "11987654321",
    email: "carlos.mendonca@email.com",
    vehicleInterest: "Honda Civic EXL 2023",
    status: "atendimento",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 3 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 2 * 3600 * 1000).toISOString(),
    origin: "instagram",
    estimatedValue: 149900,
    notes: "Interesse confirmado, solicitou proposta com entrada de 50%.",
  },
  {
    id: "l-006",
    name: "Ricardo Lima",
    phone: "11965432109",
    email: "rlima@empresa.com.br",
    vehicleInterest: "Toyota Corolla XEI 2022",
    status: "atendimento",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 5 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 4 * 3600 * 1000).toISOString(),
    origin: "whatsapp",
    estimatedValue: 134900,
    notes: "Aguardando fotos detalhadas do interior.",
  },
  {
    id: "l-007",
    name: "Fernanda Souza",
    phone: "21976543210",
    email: "fernanda.souza@email.com",
    vehicleInterest: "Jeep Compass Limited",
    status: "atendimento",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 8 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 6 * 3600 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 185000,
    notes: "Cliente corporativa querendo utilitário com tração 4x4.",
  },
  {
    id: "l-008",
    name: "Paulo Henrique",
    phone: "41943210987",
    email: "pauloh@gmail.com",
    vehicleInterest: "Chevrolet Onix LTZ 2022",
    status: "atendimento",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 16 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 8 * 3600 * 1000).toISOString(),
    origin: "icarros",
    estimatedValue: 82900,
    notes: "Primeiro contato realizado com sucesso.",
  },
  {
    id: "l-009",
    name: "Lucas Antunes",
    phone: "11944445678",
    email: "lucas.antunes@email.com",
    vehicleInterest: "Jeep Renegade Trailhawk 2023",
    status: "atendimento",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 12 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 3 * 3600 * 1000).toISOString(),
    origin: "patio_balcao",
    estimatedValue: 135000,
    notes: "Visitou o pátio presencialmente com a esposa.",
  },

  // --- 3. Test-Drive / Visita Agendada ---
  {
    id: "l-010",
    name: "Bruno Alcantara",
    phone: "11933332222",
    email: "bruno.alcantara@email.com",
    vehicleInterest: "Jeep Compass Série S 2022",
    status: "visita",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 7 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 5 * 3600 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 178000,
    notes: "Test-drive agendado para hoje às 16:30.",
  },
  {
    id: "l-011",
    name: "Carlos Eduardo",
    phone: "11922223333",
    email: "carlos.eduardo@email.com",
    vehicleInterest: "VW Nivus Highline 2023",
    status: "visita",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 26 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 8 * 3600 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 128000,
    notes: "Visita de Test-Drive concluída ontem sem registro de proposta.",
  },
  {
    id: "l-012",
    name: "Beatriz Rocha",
    phone: "51932109876",
    email: "beatriz.rocha@email.com",
    vehicleInterest: "Fiat Strada Volcano CD Aut.",
    status: "visita",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 18 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 12 * 3600 * 1000).toISOString(),
    origin: "indicacao",
    estimatedValue: 112900,
    notes: "Visita confirmada para sábado pela manhã.",
  },
  {
    id: "l-013",
    name: "Gustavo Ferreira",
    phone: "62921098765",
    email: "gustavo.f@hotmail.com",
    vehicleInterest: "Hyundai HB20 Platinum Plus",
    status: "visita",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 20 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 14 * 3600 * 1000).toISOString(),
    origin: "whatsapp",
    estimatedValue: 99900,
    notes: "Test-drive realizado, avaliando simulação.",
  },
  {
    id: "l-014",
    name: "Amanda Toledo",
    phone: "11911114444",
    email: "amanda.toledo@email.com",
    vehicleInterest: "Volkswagen Polo GTS 2023",
    status: "visita",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 10 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 2 * 3600 * 1000).toISOString(),
    origin: "olx",
    estimatedValue: 115000,
    notes: "Gostou do veículo no pátio, agendou retorno.",
  },

  // --- 4. Avaliação do Usado na Troca e Propostas (4 sem follow-up > 24h) ---
  {
    id: "l-015",
    name: "Luciana Prado",
    phone: "11999995555",
    email: "luciana.prado@email.com",
    vehicleInterest: "Volkswagen T-Cross Highline",
    status: "proposta",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 48 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 30 * 3600 * 1000).toISOString(),
    origin: "indicacao",
    estimatedValue: 126000,
    notes: "Dando Onix Premier 2021 na troca de um T-Cross Highline. Análise F&I Banco Itaú.",
    proposalFi: true,
  },
  {
    id: "l-016",
    name: "Rodrigo Meirelles",
    phone: "11988886666",
    email: "rodrigo.meirelles@email.com",
    vehicleInterest: "Honda HR-V Advance",
    status: "proposta",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 52 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 36 * 3600 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 159000,
    notes: "Avaliação do usado na troca (HB20 2019).",
  },
  {
    id: "l-017",
    name: "Mariana Albuquerque",
    phone: "47998877665",
    email: "mariana.albuquerque@gmail.com",
    vehicleInterest: "Toyota Corolla Altis Hybrid",
    status: "proposta",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 40 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 28 * 3600 * 1000).toISOString(),
    origin: "webmotors",
    estimatedValue: 162000,
    notes: "Entrada R$ 40k + 48x BV Financeira. Ficha bancária aprovada no Banco BV sem envio de contrato há 18h.",
    proposalFi: true,
  },
  {
    id: "l-018",
    name: "Thiago Ribeiro",
    phone: "11977773333",
    email: "thiago.ribeiro@email.com",
    vehicleInterest: "Chevrolet Tracker Premier 2023",
    status: "proposta",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 44 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 32 * 3600 * 1000).toISOString(),
    origin: "whatsapp",
    estimatedValue: 119900,
    notes: "Ficha bancária em análise mesa Santander.",
    proposalFi: true,
  },

  // --- 5. Mesa de Crédito / F&I Adicionais (Totalizando 5 fichas F&I ativas) ---
  {
    id: "l-019",
    name: "Roberto Silveira",
    phone: "21988887777",
    email: "roberto.silveira@outlook.com",
    vehicleInterest: "Jeep Commander Limited",
    status: "proposta",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 24 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 4 * 3600 * 1000).toISOString(),
    origin: "telefone",
    estimatedValue: 215000,
    notes: "Ficha bancária em análise mesa F&I Banco Itaú.",
    proposalFi: true,
  },
  {
    id: "l-020",
    name: "Aline Gomes",
    phone: "71910987654",
    email: "aline.gomes@empresa.com",
    vehicleInterest: "Honda Civic Touring 2022",
    status: "proposta",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 22 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 6 * 3600 * 1000).toISOString(),
    origin: "telefone",
    estimatedValue: 149000,
    notes: "Ficha bancária aprovada Banco BV aguardando entrada.",
    proposalFi: true,
  },
  {
    id: "l-021",
    name: "Eduardo Castro",
    phone: "85900876543",
    email: "edu.castro@outlook.com",
    vehicleInterest: "Fiat Fastback Limited 2023",
    status: "proposta",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 30 * 3600 * 1000).toISOString(),
    lastContactAt: new Date(now - 5 * 3600 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 136000,
    notes: "Proposta em andamento com análise de crédito.",
  },

  // --- 6. Vendas Concluídas no Ciclo (12 Vendas Ganhas) ---
  {
    id: "l-022",
    name: "André Vasconcelos",
    phone: "11988880001",
    email: "andre.v@email.com",
    vehicleInterest: "BMW 320i M Sport",
    status: "fechado",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 5 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 2 * 86400 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 269000,
    notes: "Venda concluída com financiamento Santander.",
  },
  {
    id: "l-023",
    name: "Patrícia Vieira",
    phone: "91889765432",
    email: "patricia.vieira@uol.com.br",
    vehicleInterest: "Toyota Corolla XEi 2022",
    status: "fechado",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 6 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 3 * 86400 * 1000).toISOString(),
    origin: "olx",
    estimatedValue: 134900,
    notes: "Venda fechada com pagamento à vista via TED.",
  },
  {
    id: "l-024",
    name: "Marcelo Fonseca",
    phone: "11988880003",
    email: "marcelo.f@email.com",
    vehicleInterest: "Fiat Fastback Limited",
    status: "fechado",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 7 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 3 * 86400 * 1000).toISOString(),
    origin: "instagram",
    estimatedValue: 136000,
    notes: "Entregue com pacote de acessórios da concessionária.",
  },
  {
    id: "l-025",
    name: "Camila Duarte",
    phone: "11988880004",
    email: "camila.d@email.com",
    vehicleInterest: "Nissan Kicks Exclusive",
    status: "fechado",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 8 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 4 * 86400 * 1000).toISOString(),
    origin: "webmotors",
    estimatedValue: 118000,
    notes: "Contrato assinado e veículo faturado.",
  },
  {
    id: "l-026",
    name: "Marcos Silva",
    phone: "11988880005",
    email: "marcos.s@email.com",
    vehicleInterest: "Jeep Compass Limited",
    status: "fechado",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 10 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 5 * 86400 * 1000).toISOString(),
    origin: "icarros",
    estimatedValue: 185000,
    notes: "Financiamento BV Financeira aprovado.",
  },
  {
    id: "l-027",
    name: "Letícia Ramos",
    phone: "11988880006",
    email: "leticia.r@email.com",
    vehicleInterest: "Volkswagen T-Cross Highline",
    status: "fechado",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 12 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 6 * 86400 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 129900,
    notes: "Compra com seminovo na troca.",
  },
  {
    id: "l-028",
    name: "Daniel Moreira",
    phone: "11988880007",
    email: "daniel.m@email.com",
    vehicleInterest: "Honda Civic EXL",
    status: "fechado",
    sellerName: "Rafael Alves",
    createdAt: new Date(now - 14 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 7 * 86400 * 1000).toISOString(),
    origin: "whatsapp",
    estimatedValue: 149900,
    notes: "Pagamento com entrada + consórcio Porto Seguro.",
  },
  {
    id: "l-029",
    name: "Vinícius Prado",
    phone: "11988880008",
    email: "vinicius.p@email.com",
    vehicleInterest: "Chevrolet Tracker Premier",
    status: "fechado",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 15 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 8 * 86400 * 1000).toISOString(),
    origin: "olx",
    estimatedValue: 119900,
    notes: "Venda rápida concluída em 3 dias.",
  },
  {
    id: "l-030",
    name: "Fabiana Nogueira",
    phone: "11988880009",
    email: "fabiana.n@email.com",
    vehicleInterest: "Hyundai Creta Ultimate",
    status: "fechado",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 16 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 9 * 86400 * 1000).toISOString(),
    origin: "indicacao",
    estimatedValue: 144000,
    notes: "Cliente indicada por comprador anterior.",
  },
  {
    id: "l-031",
    name: "Rodrigo Santos",
    phone: "11988880010",
    email: "rodrigo.s@email.com",
    vehicleInterest: "Fiat Strada Volcano",
    status: "fechado",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 18 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 10 * 86400 * 1000).toISOString(),
    origin: "patio_balcao",
    estimatedValue: 112900,
    notes: "Compra para empresa CNPJ com faturamento direto.",
  },
  {
    id: "l-032",
    name: "Vanessa Lima",
    phone: "11988880011",
    email: "vanessa.l@email.com",
    vehicleInterest: "Honda HR-V EXL",
    status: "fechado",
    sellerName: "Camila Rocha",
    createdAt: new Date(now - 20 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 11 * 86400 * 1000).toISOString(),
    origin: "site",
    estimatedValue: 139900,
    notes: "Venda concluída com garantia estendida.",
  },
  {
    id: "l-033",
    name: "Guilherme Pires",
    phone: "11988880012",
    email: "guilherme.p@email.com",
    vehicleInterest: "Toyota Corolla Altis",
    status: "fechado",
    sellerName: "Lucas Mendes",
    createdAt: new Date(now - 22 * 86400 * 1000).toISOString(),
    lastContactAt: new Date(now - 12 * 86400 * 1000).toISOString(),
    origin: "webmotors",
    estimatedValue: 162000,
    notes: "Ficha bancária aprovada e entregue.",
  },
];

// ---------------------------------------------------------------------------
// Clientes de demonstração (Carteira CRM)
// ---------------------------------------------------------------------------

export const mockClients: Client[] = [
  {
    id: "c-001",
    name: "Mariana Souza",
    phone: "47998877665",
    email: "mariana.souza@gmail.com",
    document: "123.456.789-00",
    status: "comprador",
    sellerName: "Rafael Alves",
    vehiclePreference: "Corolla Cross XRE",
    totalPurchased: 168900,
    purchasesCount: 1,
    lastInteractionAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Cliente fiel, comprou SUV recentemente. Interesse em troca após 2 anos.",
  },
  {
    id: "c-002",
    name: "Carlos Mendonça",
    phone: "11987654321",
    email: "carlos.mendonca@email.com",
    document: "234.567.890-11",
    status: "ativo",
    sellerName: "Rafael Alves",
    vehiclePreference: "Honda Civic EXL",
    totalPurchased: 0,
    purchasesCount: 0,
    lastInteractionAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    notes: "Aguardando proposta de financiamento do banco Santander.",
  },
  {
    id: "c-003",
    name: "Roberto Silveira",
    phone: "21988887777",
    email: "roberto.silveira@outlook.com",
    document: "345.678.901-22",
    status: "comprador",
    sellerName: "Camila Dias",
    vehiclePreference: "Jeep Compass Limited",
    totalPurchased: 354800,
    purchasesCount: 2,
    lastInteractionAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Colecionador de utilitários, comprou dois veículos na loja.",
  },
  {
    id: "c-004",
    name: "Aline Gomes",
    phone: "71910987654",
    email: "aline.gomes@empresa.com",
    document: "456.789.012-33",
    status: "ativo",
    sellerName: "Camila Dias",
    vehiclePreference: "Volkswagen T-Cross",
    totalPurchased: 0,
    purchasesCount: 0,
    lastInteractionAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    notes: "Test-drive agendado para o próximo sábado às 10h.",
  },
  {
    id: "c-005",
    name: "Eduardo Castro",
    phone: "85900876543",
    email: "edu.castro@outlook.com",
    document: "567.890.123-44",
    status: "inativo",
    sellerName: "Lucas Santana",
    vehiclePreference: "Fiat Strada Volcano",
    totalPurchased: 112900,
    purchasesCount: 1,
    lastInteractionAt: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Sem contato há mais de 3 meses. Campanha de reativação necessária.",
  },
  {
    id: "c-006",
    name: "Patrícia Vieira",
    phone: "91889765432",
    email: "patricia.vieira@uol.com.br",
    document: "678.901.234-55",
    status: "comprador",
    sellerName: "Rafael Alves",
    vehiclePreference: "Renault Kwid Intense",
    totalPurchased: 59900,
    purchasesCount: 1,
    lastInteractionAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    notes: "Primeiro carro comprado para o filho recém-habilitado.",
  },
];

/**
 * Cria uma nova entidade Client a partir dos dados do formulário.
 */
export function createClient(data: ClientFormData): Client {
  return {
    id: `c-${Date.now()}`,
    ...data,
    totalPurchased: 0,
    purchasesCount: 0,
    lastInteractionAt: new Date().toISOString(),
  };
}

